export const SKILLS = [
    { id: "skl-001", title: "Design Thinking", type: "hard-skill" },
    { id: "skl-002", title: "Systems Thinking", type: "hard-skill" },
    { id: "skl-003", title: "User Research", type: "hard-skill" },
    { id: "skl-004", title: "UX / UI", type: "hard-skill" },
    { id: "skl-005", title: "Rapid Prototyping", type: "hard-skill" },
    { id: "skl-006", title: "Motion Graphics", type: "hard-skill" },
    // { id: "skl-007", title: "3D Modeling", type: "hard-skill" },
    { id: "skl-008", title: "Creativity", type: "soft-skill" },
    { id: "skl-009", title: "Effective Communication", type: "soft-skill" },
    { id: "skl-010", title: "Problem-Solving", type: "soft-skill" },
    { id: "skl-011", title: "Teamwork", type: "soft-skill" },
    { id: "skl-012", title: "Figma", type: "design", image: "icon-figma.svg" },
    { id: "skl-013", title: "Photoshop", type: "design", image: "icon-photoshop.svg" },
    { id: "skl-014", title: "Illustrator", type: "design", image: "icon-illustrator.svg" },
    { id: "skl-015", title: "Rive", type: "design", image: "icon-rive.jpeg" },
    { id: "skl-016", title: "Blender", type: "design", image: "icon-blender.svg" },
    { id: "skl-017", title: "3ds Max", type: "design", image: "icon-3dsmax.png" },
    { id: "skl-018", title: "HTML", type: "develop", image: "icon-html.svg" },
    { id: "skl-019", title: "CSS", type: "develop", image: "icon-css.svg" },
    { id: "skl-020", title: "TypeScript", type: "develop", image: "icon-ts.svg" },
    { id: "skl-021", title: "React", type: "develop", image: "icon-react.svg" },
    { id: "skl-022", title: "Next", type: "develop", image: "icon-next.png" },
    { id: "skl-023", title: "ThreeJS", type: "develop", image: "icon-threejs.svg" },
]